### ISSUE TITLE
Mongobee fails on mongo 4.2 with 'not authorized on testdb to execute command { find: "system.indexes", filter: { ns: "testdb.dbchangelog", key: { changeId: 1, author: 1 } } ...'

### ISSUE THREAD

**Issue by amitsadafule** [mongobee/mongobee#104]
I have user with `readWrite` role in mongo 4.0.2. Mongobee initialises perfectly on this mongo version. Recently I have upgraded mongo to 4.2.0. After this upgrade, application is not starting and failing with 
`Caused by: com.mongodb.MongoQueryException: Query failed with error code 13 and error message 'not authorized on testdb to execute command { find: "system.indexes", filter: { ns: "testdb.dbchangelog", key: { changeId: 1, author: 1 } }, limit: 1, singleBatch: true, $db: "testdb", $clusterTime: { clusterTime: Timestamp(1566896122, 5), signature: { hash: BinData(0, 271270B91FA19BEB1F07235390A2C2A935F53038), keyId: 6683394885568954369 } }, lsid: { id: UUID("93ab8684-2380-4580-9556-509a962df832") }, $readPreference: { mode: "primaryPreferred" } }' on server 10.x.x.x:27017
	at com.mongodb.operation.FindOperation$1.call(FindOperation.java:735) ~[mongo-java-driver-3.11.0.jar!/:na]
	at com.mongodb.operation.FindOperation$1.call(FindOperation.java:725) ~[mongo-java-driver-3.11.0.jar!/:na]
	at com.mongodb.operation.OperationHelper.withReadConnectionSource(OperationHelper.java:463) ~[mongo-java-driver-3.11.0.jar!/:na]
	at com.mongodb.operation.FindOperation.execute(FindOperation.java:725) ~[mongo-java-driver-3.11.0.jar!/:na]
	at com.mongodb.operation.FindOperation.execute(FindOperation.java:89) ~[mongo-java-driver-3.11.0.jar!/:na]
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:189) ~[mongo-java-driver-3.11.0.jar!/:na]
	at com.mongodb.client.internal.FindIterableImpl.first(FindIterableImpl.java:205) ~[mongo-java-driver-3.11.0.jar!/:na]
	at com.github.mongobee.dao.ChangeEntryIndexDao.findRequiredChangeAndAuthorIndex(ChangeEntryIndexDao.java:35) ~[mongobee-0.13.jar!/:na]
	at com.github.mongobee.dao.ChangeEntryDao.ensureChangeLogCollectionIndex(ChangeEntryDao.java:121) ~[mongobee-0.13.jar!/:na]
	at com.github.mongobee.dao.ChangeEntryDao.connectMongoDb(ChangeEntryDao.java:61) ~[mongobee-0.13.jar!/:na]
	at com.github.mongobee.dao.ChangeEntryDao.connectMongoDb(ChangeEntryDao.java:72) ~[mongobee-0.13.jar!/:na]
	at com.github.mongobee.Mongobee.execute(Mongobee.java:145) ~[mongobee-0.13.jar!/:na]
	at com.github.mongobee.Mongobee.afterPropertiesSet(Mongobee.java:126) ~[mongobee-0.13.jar!/:na]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1804) ~[spring-beans-5.1.2.RELEASE.jar!/:5.1.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1741) ~[spring-beans-5.1.2.RELEASE.jar!/:5.1.2.RELEASE]
	... 24 common frames omitted`

After some googling, it seems that, I need to attach `dbAdmin` role to user. But this is dangerous to attach this role to application db user.

Please help, in resolving this

**Comment by amitsadafule** [comment]
https://docs.mongodb.com/manual/reference/system-collections/#%3Cdatabase%3E.system.indexes

As per this system.indexes is deprecated.

**Comment by mkulle** [comment]
@lstolowski 

I have the same issue.

I found deprecated code here:

https://github.com/mongobee/mongobee/blob/4e1ec5e381121fc9e5ad54881c84029114bafa52/src/main/java/com/github/mongobee/dao/ChangeEntryIndexDao.java

**Comment by amitsadafule** [comment]
It came out to be privilege issue.. I have answered it https://stackoverflow.com/questions/57721306/getting-not-authorized-for-query-on-testdb-system-indexes-src-mongo-db-commands/57870446#57870446

**Comment by amitsadafule** [comment]
@mongobee : I have raised below PR for above issue.
https://github.com/mongobee/mongobee/pull/106

**Comment by rohitgubrele8** [comment]
Version 0.9 of Mongobee is an older version on MongoTemplate witch has been discontinued from Mongo 4.2. Extend the Mongobee class and update the MongoTemplate object to a newer Mongotemplate constructor( MethodName -> "executeChangeSetMethod"). This resolved the problem for me without any changes in roles.

**Comment by jjalvarezl** [comment]
Hi.

I'm using mongobee on a mongodb 4.4 version. Anyway this worked for me:

> @mongobee : I have raised below PR for above issue.
> #106

I'm not using gradle, so I builded my solution in maven. Here is like the same but in the pom.xml file I've remplaced this:

```xml
<dependency>
	<groupId>com.github.mongobee</groupId>
	<artifactId>mongobee</artifactId>
	<version>0.13</version>
	<exclusions>
		<exclusion>
			<groupId>org.mongodb</groupId>
			<artifactId>mongo-java-driver</artifactId>
		</exclusion>
	</exclusions>
</dependency>
```

Into this:

```xml
<dependency>
	<groupId>com.github.dalet-oss</groupId>
	<artifactId>mongobee</artifactId>
	<version>1.0.4</version>
	<exclusions>
		<exclusion>
			<groupId>org.mongodb</groupId>
			<artifactId>mongo-java-driver</artifactId>
		</exclusion>
	</exclusions>
</dependency>
```

And worked like a champ. I hope it would be useful.

Thanks to @amitsadafule for your improving mongobee.

**Comment by vaibhavgaikwad** [comment]
> Hi.
> 
> I'm using mongobee on a mongodb 4.4 version. Anyway this worked for me:
> 
> > @mongobee : I have raised below PR for above issue.
> > #106
> 
> I'm not using gradle, so I builded my solution in maven. Here is like the same but in the pom.xml file I've remplaced this:
> 
> ```
> <dependency>
> 	<groupId>com.github.mongobee</groupId>
> 	<artifactId>mongobee</artifactId>
> 	<version>0.13</version>
> 	<exclusions>
> 		<exclusion>
> 			<groupId>org.mongodb</groupId>
> 			<artifactId>mongo-java-driver</artifactId>
> 		</exclusion>
> 	</exclusions>
> </dependency>
> ```
> 
> Into this:
> 
> ```
> <dependency>
> 	<groupId>com.github.dalet-oss</groupId>
> 	<artifactId>mongobee</artifactId>
> 	<version>1.0.4</version>
> 	<exclusions>
> 		<exclusion>
> 			<groupId>org.mongodb</groupId>
> 			<artifactId>mongo-java-driver</artifactId>
> 		</exclusion>
> 	</exclusions>
> </dependency>
> ```
> 
> And worked like a champ. I hope it would be useful.
> 
> Thanks to @amitsadafule for your improving mongobee.

Thanks You save my day....

**Comment by gelfandbein** [comment]
sometimes need to 'votes=0' on hidden replicaSet member, like delay secondary in my way :)
