### ISSUE TITLE
Error creating bean with name 'mongobee' 

### ISSUE THREAD

**Issue by AndriOsta** [mongobee/mongobee#47]
I can't create a bean.Problem is in ChangeEntryDao. Please fix it,thanks

**Comment by lstolowski** [comment]
Hi

which version do you use (release number or checked out from gitlab)?
Could you please paste a Stacktrace or some logs?

**Comment by AndriOsta** [comment]
@lstolowski 
I'm using   <version>0.12</version>
Yep,sure:
Exception in thread "main" org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'mongobee' defined in com.leancase.app.Application: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.github.mongobee.Mongobee]: Factory method 'mongobee' threw exception; nested exception is java.lang.NoClassDefFoundError: org/bson/conversions/Bson
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:599)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1111)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1006)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:504)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:303)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:299)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:762)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:757)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:480)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:691)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:321)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:961)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:950)
	at com.leancase.app.Application.main(Application.java:23)
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.github.mongobee.Mongobee]: Factory method 'mongobee' threw exception; nested exception is java.lang.NoClassDefFoundError: org/bson/conversions/Bson
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588)
	... 17 more
Caused by: java.lang.NoClassDefFoundError: org/bson/conversions/Bson
	at com.github.mongobee.Mongobee.<init>(Mongobee.java:84)
	at com.leancase.app.Application.mongobee(Application.java:35)
	at com.leancase.app.Application$$EnhancerBySpringCGLIB$$c4731eac.CGLIB$mongobee$0(<generated>)
	at com.leancase.app.Application$$EnhancerBySpringCGLIB$$c4731eac$$FastClassBySpringCGLIB$$a3512ea4.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:309)
	at com.leancase.app.Application$$EnhancerBySpringCGLIB$$c4731eac.mongobee(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162)
	... 18 more
Caused by: java.lang.ClassNotFoundException: org.bson.conversions.Bson
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 30 more

**Comment by AndriOsta** [comment]
@lstolowski  
Reused version to 0.9 and know evrything is ok

**Comment by AndriOsta** [comment]
@lstolowski
Reused version to 0.9 and know evrything is ok

**Comment by lstolowski** [comment]
I will take a look at the current version.

**Comment by lstolowski** [comment]
Hi, It looks like a problem with building your app or some mess with your maven's dependencies... Did you try to clean your project?
Maybe take a look at http://stackoverflow.com/questions/40912639/mongodb-with-java-exception-in-thread-main-java-lang-noclassdeffounderror-org

In mongobee:0.12 I changed mongo-java-driver to 3.3.0 (from 2.12.2). Maybe mongo driver has some dependencies changed and your maven lost a bit... I'm guessing...
