### ISSUE TITLE
Mongobees performs cluster command to wrong connection

### ISSUE THREAD

**Issue by inthegarage** [mongobee/mongobee#68]
When running mongobees, I create a runner and it runs and executes all the tests just fine. Our Mongo is "in the cloud" and mongobees connects just fine.

However at the end of the run it always goes away and does some "cluster" work. I'm not sure what this is for as it has already executed all the migrations and saved (correctly) the dbchangelog.
I see the following:

```
2017-10-26 16:47:17.551  INFO 18825 --- [           main] com.github.mongobee.Mongobee             : Mongobee has finished his job.
2017-10-26 16:47:17.680  INFO 18825 --- [           main] org.mongodb.driver.cluster               : Cluster created with settings {hosts=[localhost:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=500}
2017-10-26 16:47:17.701  INFO 18825 --- [localhost:27017] org.mongodb.driver.cluster               : Exception in monitor thread while connecting to server localhost:27017

com.mongodb.MongoSocketOpenException: Exception opening socket
	at com.mongodb.connection.SocketStream.open(SocketStream.java:63) ~[mongo-java-driver-3.4.2.jar:na]
	at com.mongodb.connection.InternalStreamConnection.open(InternalStreamConnection.java:115) ~[mongo-java-driver-3.4.2.jar:na]
	at com.mongodb.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:113) ~[mongo-java-driver-3.4.2.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_121]
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.8.0_121]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[na:1.8.0_121]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_121]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_121]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_121]
	at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_121]
	at com.mongodb.connection.SocketStreamHelper.initialize(SocketStreamHelper.java:57) ~[mongo-java-driver-3.4.2.jar:na]
	at com.mongodb.connection.SocketStream.open(SocketStream.java:58) ~[mongo-java-driver-3.4.2.jar:na]
	... 3 common frames omitted
```
Note the line "mongobees has finished its job".
This will never work as my connection isn't on localhost and there isn't a mongo running in my environment in local host. How do we turn off this feature? It doesn't seem to provide any functionality.

Please advise.

**Comment by inthegarage** [comment]
This is caused by spring sticking some auto configuration. To avoid this use the following directive:

@SpringBootApplication(exclude = {MongoAutoConfiguration.class, MongoDataAutoConfiguration.class})

This is not a mongobee error.
