### ISSUE TITLE
spring-data-mongodb-2.0.0 support

### ISSUE THREAD

**Issue by ps-aux** [mongobee/mongobee#75]
Seems it does not work spring-data-mongodb-2.0.0+. `MongoTemplate` has maybe different constructor there.

**Comment by khetho** [comment]
When using spring-boot-starter-data-mongodb version 2.0.0.RC1 the following exception is thrown

> Caused by: java.lang.NoSuchMethodError: org.springframework.data.mongodb.core.MongoTemplate.<init>(Lcom/mongodb/Mongo;Ljava/lang/String;)V
	at com.github.mongobee.Mongobee.executeChangeSetMethod(Mongobee.java:224) ~[mongobee-0.13.jar:na]
	at com.github.mongobee.Mongobee.executeMigration(Mongobee.java:185) ~[mongobee-0.13.jar:na]
	at com.github.mongobee.Mongobee.execute(Mongobee.java:156) ~[mongobee-0.13.jar:na]
	at com.github.mongobee.Mongobee.afterPropertiesSet(Mongobee.java:126) ~[mongobee-0.13.jar:na]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1769) ~[spring-beans-5.0.2.RELEASE.jar:5.0.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1706) ~[spring-beans-5.0.2.RELEASE.jar:5.0.2.RELEASE]
	... 28 common frames omitted

The issue is in the org.springframework.data.mongodb.core.MongoTemplate class where MongoBee expects a constructor with com/mongodb/Mongo  & java/lang/String parameters. Howver this constructor exists in Spring MonogDB only up to [12.0.0-M1](https://docs.spring.io/spring-data/mongodb/docs/2.0.0.M1/api/org/springframework/data/mongodb/core/MongoTemplate.html) . As of [2.0.0-M2](https://docs.spring.io/spring-data/mongodb/docs/2.0.0.M2/api/org/springframework/data/mongodb/core/MongoTemplate.html) the constructor with these parameters no longer exists and mongobee exits.

**Comment by groothuyse** [comment]
Additionally, Mongobee depends on Spring 4.x libraries which cause conflicts with Spring boot 2 applications. 

```
[INFO] +- com.github.mongobee:mongobee:jar:0.13:compile
[INFO] |  +- org.mongodb:mongo-java-driver:jar:3.3.0:compile
[INFO] |  +- org.springframework:spring-beans:jar:4.0.6.RELEASE:compile
[INFO] |  +- org.springframework:spring-context:jar:4.0.6.RELEASE:compile
```

**Comment by khetho** [comment]
Thanks @groothuyse  for your work around. It worked like a charm for me as well. I used AbstractMongoConfiguration  to get an instance of MongoTemplate

`@Configuration
public class Config extends AbstractMongoConfiguration {

    @Value("${spring.data.mongodb.uri}")
    private String uri;

    @Override
    public MongoClient mongoClient() {
        return new MongoClient(new MongoClientURI(uri));
    }

    @Override
    protected String getDatabaseName() {
        return "db";
    }

    @Bean
    public Mongobee mongobee() throws Exception {
        Mongobee runner = new Mongobee(uri);
        runner.setDbName(getDatabaseName());
        runner.setChangeLogsScanPackage("my.changelogs");
        runner.setMongoTemplate(mongoTemplate());
        return runner;
    }
}`

**Comment by samtron3030** [comment]
This workaround work with Spring Boot 2.0.0.RELEASE as well.

**Comment by Hronom** [comment]
Yep, thanks for workaround. But also interested when you will add official support for Spring 5 and Spring Boot 2.0.0?

It's good time now, since they have official release for Spring Cloud platform.

I can try to provide PR, but it's not clear to me what workflow you wanna have to provide support for Spring 4 and 5 at the same time.

**Comment by shanedeeodonnell** [comment]
I'm getting the same error when I use runAlways = true, even with the workaround. Does anyone have a tweak to @groothuyse and @khetho's workarounds while we wait for the PR to be merged?

**Comment by redent** [comment]
Just a small update, if you set the MongoTemplate you don't need to pass the URI to the constructor. You still need to pass the database name, but the config is very simple. If you're using Spring Data, MongoTemplate can be injected by Spring, so no need to extend AbstractMongoConfiguration This code works for Spring Boot 2.0 (Kotlin):

~~~
@Configuration
class MongoBeeConfig(
        val template: MongoTemplate,
        @Value("\${spring.data.mongodb.database}") val dbName: String
) {

    @Bean
    fun mongoBee(): Mongobee {
        return Mongobee()
            .setDbName(dbName)
            .setChangeLogsScanPackage(this.javaClass.`package`.name)
            .setMongoTemplate(template)
    }
}
~~~

**Comment by oharsta** [comment]
Bit late to this party, but if you use the no-arg constructor of `Mongobee` it defaults to using the default host and port. If you are running against a remote mongo cluster or any other instance where the defaults not apply you need to pass in the full URI using `MongoClientURI` or create a separate `MongoClient` which is used by `Mongobee` to create the `dbchangelog` collection.

**Comment by blafoo** [comment]
@ps-aux Have a look at [MongoBumblebee](https://github.com/hdisysteme/MongoBumblebee). It's available at Maven Central and works with Spring Boot 3 and Java 17.
